# Setup
title:               Akhil's Blog
tagline:             'Thoughts, Ideas, Essays & Views'
description:         'A blog on tech, product, finance & sanskrit'
url:                 http://akhil.blog
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Akhil Agrawal
  url:               https://twitter.com/akhilbharatiya
  email:             akhilatmail+blog@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-XX8EMD13K7
