# Setup
title:               Akhil's Blog
tagline:             'Blog for thoughts, essays and views'
description:         'A journey through tech, product & sans'
url:                 http://akhil.blog
baseurl:             'http://agrawalakhil.github.io/akhil.blog'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Akhil Agrawal
  url:               https://twitter.com/akhilbharatiya
  email:             akhilatmail@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
